version: '3.8'

services:
  nginx:
    build: ./nginx
    container_name: ocr_nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - ocr_network

  app:
    build: ./ocr_app
    container_name: ocr_flask_app
    restart: always
    expose:
      - "5000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_started
    volumes:
      - ./ocr_app:/app
    networks:
      - ocr_network

  db:
    image: postgres:15-alpine
    container_name: ocr_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ocr_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama
    container_name: ocr_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - ocr_network
    # This command will run on first start to pull the model automatically
    entrypoint: /bin/sh -c "ollama serve & ollama pull llava; wait"


volumes:
  postgres_data:
  ollama_data:

networks:
  ocr_network:
    driver: bridge