# Upstream for our Flask application
upstream ocr_app {
    server app:5000;
    # You could add more app servers here for load balancing
    # server app2:5000;
}

server {
    listen 80;

    # Route requests for static files directly to the file system
    location /static {
        alias /app/static;
        expires 30d;
        access_log off;
    }

    # Route all other requests to the Flask application
    location / {
        proxy_pass http://ocr_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}